### ISSUE TITLE
broken link at end of lessons

### ISSUE THREAD

**Issue by cwsmith** [xsdk-project/ATPESC2018HandsOnLessons#1]
The 'Back to all HandsOnLessons' link at the bottom of the [mfem](https://xsdk-project.github.io/ATPESC2018HandsOnLessons/lessons/mfem_convergence/) and [superlu-mfem](https://xsdk-project.github.io/ATPESC2018HandsOnLessons/lessons/superlu_mfem/) lessons is broken (others?).  Should this link be removed and just keep the (working) 'Back to all ATPESC 2018 Lessons' link?

**Comment by markcmiller86** [comment]
Ooopes. That is a holdover from my port from the older lessons. I shuld have removed that older link.

Will do so shortly.

Also, I realized by {{site.handson_root}} trick isn't quite right either and will fix.

Mark
"Cameron Smith" wrote:

The 'Back to all HandsOnLessons' link at the bottom of the mfem<https://xsdk-project.github.io/ATPESC2018HandsOnLessons/lessons/mfem_convergence/> and superlu-mfem<https://xsdk-project.github.io/ATPESC2018HandsOnLessons/lessons/superlu_mfem/> lessons is broken (others?). Should this link be removed and just keep the (working) 'Back to all ATPESC 2018 Lessons' link?

**Comment by cwsmith** [comment]
fixed
